initial_lr:
  value: 1e-2
  type: float
  description: "Initial learning rate"
weight_decay:
  value: 3e-5
  type: float
  description: "Weight decay for optimizer"
oversample_foreground_percent:
  value: 0.33
  type: float
  description: "Percent of batch to be filled with foreground patches"
probabilistic_oversampling:
  value: false
  type: bool
  description: "Whether to use probabilistic oversampling"
num_iterations_per_epoch:
  value: 250
  type: int
  description: "Number of iterations per epoch"
num_val_iterations_per_epoch:
  value: 50
  type: int
  description: "Number of validation iterations per epoch"
num_epochs:
  value: 150
  type: int
  description: "Total number of epochs"
current_epoch:
  value: 0
  type: int
  description: "Current epoch (used for resuming training)"
enable_deep_supervision:
  value: true
  type: bool
  description: "Whether to enable deep supervision"
experiment_name:
  value: "nnUnet-default"
  type: str
  description: "Name of the MLFlow experiment name."
tracking_uri:
  value: "https://mlflow.spectomedical.com"
  type: str
  description: "Address of the MLFlow server"
checkpointing_bucket:
  value: "specto-ai-ts-checkpoints"
  type: str
  description: "S3 bucket name where the checkpoints are being written to."
mlflow_run_id:
  value: "e0074c4a92b349948e222f32cb5ab77d"
  type: str
  description: "Run id of MLFlow to identify the checkpoint to resume from."
aws_region:
  value: "eu-central-1"
  type: str
  description: "AWS region to select the respective S3 endpoint."