name: Run nnunet tests on all OS
on:
  push:
    paths-ignore:
      - '**.md'
jobs:

  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-15-intel, macos-26-intel]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Download and extract weights and download example file
      # use python for everything to be cross-platform (avoids issues with curl, unzip, and path separators on Windows)
      run: |
        python -c "import os, urllib.request, zipfile; d = os.path.join(os.path.expanduser('~'), 'github_actions_nnunet', 'results'); os.makedirs(d, exist_ok=True); z = os.path.join(d, 'tmp.zip'); urllib.request.urlretrieve('https://github.com/wasserth/TotalSegmentator/releases/download/v2.0.0-weights/Dataset300_body_6mm_1559subj.zip', z); zipfile.ZipFile(z).extractall(d); os.remove(z)"

    - name: Install dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: |
        python -m pip install --upgrade pip
        pip install pytest Cython
        pip install torch -f https://download.pytorch.org/whl/cpu
        pip install .

    - name: Install dependencies on Windows / MacOS
      if: (runner.os == 'Windows' || runner.os == 'macOS') && !contains(matrix.os, 'intel')
      run: |
        python -m pip install --upgrade pip
        pip install pytest Cython
        pip install .

    - name: Install dependencies on Intel MacOS
      if: contains(matrix.os, 'intel')
      run: |
        python -m pip install --upgrade pip
        pip install pytest Cython
        pip install ".[intel_macos]"

    - name: Run test script
      run: python nnunetv2/tests/integration_tests/run_nnunet_inference.py
